### ISSUE TITLE
Some Meteor Redux example to add.

### ISSUE THREAD

**Issue by SenerDemiral** [xgrommx/awesome-redux#28]
https://github.com/AdamBrodzinski/meteor-flux-leaderboard/tree/redux

**Comment by xgrommx** [comment]
@SenerDemiral you can do it! Welcome to PR.

**Comment by SenerDemiral** [comment]
I do not know how to do!

**Comment by xgrommx** [comment]
Ok, I'll do it.

**Comment by xgrommx** [comment]
Have done!
