### ISSUE TITLE
add redux-fluent

### ISSUE THREAD

**Issue by hitmands** [xgrommx/awesome-redux#316]
Hi, I've been working at this package https://github.com/Code-Y/redux-fluent and I'd like to add it to the list of redux resources, so I could get some more feedback.

**Comment by armenr** [comment]
@hitmands - great library you've written! Instantly a fan of this :)

Simple, to the point, small, functional, and useful. I'll take this for a test-drive in a project of mine and will ping on the project repo in case of any bugs or observations/issues. Thanks for your thoughtful work!
