### ISSUE TITLE
Add redux-undo

### ISSUE THREAD

**Issue by omnidan** [xgrommx/awesome-redux#58]
Hi!

What do you think about adding [redux-undo](https://github.com/omnidan/redux-undo) and/or [redux-undo-boilerplate](https://github.com/omnidan/redux-undo-boilerplate)? :grin:

**Comment by xgrommx** [comment]
@omnidan Welcome) Just provide me your PR. But redux-undo was added earlier. You can prepare pull request with redux-undo-boilerplate and I'll merge this one.

**Comment by omnidan** [comment]
@xgrommx ah, that's cool :) thanks, I created a PR: https://github.com/xgrommx/awesome-redux/pull/59
