### ISSUE TITLE
Examples need some cleanup and categorisation

### ISSUE THREAD

**Issue by luandro** [xgrommx/awesome-redux#7]
The examples list is very messy. A lot of the examples don't even have a README, or have stopped their progress midway. There could also be some categorisation: Official examples, GraphQL, Universal (Isomorphic). These are just some obvious ones I saw really quick.

**Comment by xgrommx** [comment]
I know, look at this comment https://github.com/xgrommx/awesome-redux/issues/2#issuecomment-123651477

**Comment by luandro** [comment]
Looks a hell of a lot better. Still needs some cleanup, but the :metal: symbol makes it a lot more readable.
