### ISSUE TITLE
Este

### ISSUE THREAD

**Issue by steida** [xgrommx/awesome-redux#79]
Maybe https://github.com/este/este should be added, as it illustrate well maintained React dev stack based on Redux, with support both for React and React Native in one project.

**Comment by xgrommx** [comment]
You saw this one https://github.com/xgrommx/awesome-redux#react---a-javascript-library-for-building-user-interfaces? This paragraph contains `Frameworks` category.

**Comment by steida** [comment]
Ohh, sorry :-)
